services:
  datascience:
    image: gnasello/datascience-env:2025-09-18
    container_name: datascience-env
    user: root
    ports:
      - 8888:8888
    environment:
    #- NB_UID={NB_UID}
    #- NB_GID={NB_GID}
    - CHOWN_HOME=yes
    - CHOWN_HOME_OPTS=-R
    - GRANT_SUDO=yes
    #- JUPYTER_PORT=8888